workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "GimPlay.xcodeproj" # <-- Put the name of your Xcode project here
        XCODE_SCHEME: "GimPlay" # <-- Put the name of your Xcode scheme here
        API_KEYS: $API_KEYS # <-- This will use the value from Codemagic environment variables
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create env.plist
        script: |
          cat > GimPlay/env.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>API_KEYS</key>
              <string>$API_KEYS</string>
          </dict>
          </plist>
          EOL
      - name: Build debug app
        script: | 
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - wildanfajri85@gmail.com
        notify:
          success: true
          failure: true