workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "GimPlay.xcodeproj" # <-- Put the name of your Xcode project here
        XCODE_SCHEME: "GimPlay" # <-- Put the name of your Xcode scheme here
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build debug app
        script: | 
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build/ios \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/Build/**/*.app
    publishing:
      email:
        recipients:
          - wildanfajri85@gmail.com
        notify:
          success: true
          failure: true